import { getClassIcon } from '../../data/class-icons.js';
import { arkGridCategories } from '../../data/ark-grid-categories.js';
import { getEngravingIcon } from '../../data/engraving-icons.js';

export const escape = (value = '') => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const arkCategoryIcon = (kind, slot) => {
  const category = arkGridCategories[kind]?.[slot];
  return `<span class="core-symbol" aria-hidden="true"><span>${category?.symbol || '◇'}</span>${category ? `<img src="./${escape(category.icon)}" alt="" width="49" height="49" loading="lazy" data-fallback>` : ''}</span>`;
};
export const badge = (text, tone = '') => `<span class="badge ${escape(tone)}">${escape(text)}</span>`;
export const asset = (record, size = '') => {
  const icon = record.icon || getClassIcon(record.class);
  return `<span class="asset ${size}${record.class ? ' class-asset' : ''}" aria-hidden="true"><span>${escape(record.name?.split(' ').map((word) => word[0]).join('').slice(0, 2) || record.class?.slice(0, 2) || '◇')}</span>${icon ? `<img src="./${escape(icon)}" alt="${escape(record.name || record.class || '')}" loading="lazy" data-fallback>` : ''}</span>`;
};
export const flow = (items, className = '') => `<div class="flow ${className}">${items.map((item, i) => `${i ? '<span class="arrow" aria-hidden="true">→</span>' : ''}<span class="flow-step">${escape(item)}</span>`).join('')}</div>`;
export const section = (id, number, title, description, content, controls = '') => `<section id="${id}" class="guide-section" aria-labelledby="${id}-title"><div class="section-heading"><span class="section-number">${number}</span><h2 id="${id}-title">${escape(title)}</h2>${controls}</div>${description ? `<p class="section-description">${escape(description)}</p>` : ''}${content}</section>`;
export const runeBadge = (rune, rarity) => {
  const structured = typeof rune === 'object' && rune !== null;
  const name = structured ? rune.name : rune;
  const grade = structured ? rune.rarity : rarity;
  const pending = grade === null;
  return `<span class="rune ${escape((grade || '').toLowerCase())}${structured || pending ? ' rune-detailed' : ''}"><span aria-hidden="true">◆</span> ${escape(name)} ${grade || pending ? `<small>${escape(grade || 'Rarity not specified')}</small>` : ''}</span>${structured && rune.note ? `<span class="rune-option-note">${escape(rune.note)}</span>` : ''}`;
};
export const guideHeader = (guide) => `<header class="guide-header"><div class="eyebrow">${escape(guide.class)} / ${escape(guide.build)} / ${escape(guide.variant)}</div><div class="hero-heading"><div><h1>${escape(guide.class)} <span>— ${escape(guide.build)}<br><em>${escape(guide.variant)}</em></span></h1><p>${escape(guide.version)}</p></div>${asset(guide, 'class-art guide-class-art')}</div><div class="metadata">${badge(guide.role)}${guide.requiresArkGrid ? badge('ARK GRID REQUIRED', 'purple') : ''}<span>Updated <time datetime="${escape(guide.updated)}">${escape(guide.updated)}</time></span></div></header>`;
export const buildOverview = (guide) => `<div class="overview-grid">${guide.overview.highlights.map((item, i) => `<div class="summary-card"><span class="micro">0${i + 1} / ${escape(item.label)}</span><strong>${escape(item.value)}</strong></div>`).join('')}</div><p>${escape(guide.overview.playstyle)}</p>${flow(guide.overview.flow)}${guide.requiresArkGrid ? `<aside class="notice"><strong>Ark Grid é parte da build.</strong><p>${escape(guide.requirement)}</p></aside>` : ''}`;
const coreRaritySummary = (core) => core.rarity ? `<dl class="core-rarities core-rarity-summary"><div><dt>Target Rarity</dt><dd>${badge(core.rarity)} ${badge(`${core.breakpoint}P+`)}</dd></div><div><dt>Minimum recommended for the complete setup</dt><dd>${badge(core.minimumRarity)} ${badge(`${core.breakpoint}P`)}</dd></div></dl>` : '';

export const arkCoreCard = (core, kind, sources) => {
  const detailed = core.position !== undefined;
  const points = (core.points || []).map((point) => {
    if (!detailed) return `<div class="breakpoint"><b>${point.value}P</b><p>${escape(point.text)}</p></div>`;
    return `<div class="breakpoint"><div class="breakpoint-heading"><b>${escape(point.value)}P</b>${point.label ? badge(point.label, point.tone) : ''}</div><p>${escape(point.text)}</p>${point.rarities ? `<dl class="core-rarities">${point.rarities.map((rarity) => `<div><dt>${badge(rarity.name)}</dt><dd>${escape(rarity.effect)}</dd></div>`).join('')}</dl>` : ''}${point.note ? `<p>${escape(point.note)}</p>` : ''}${point.flow ? flow(point.flow) : ''}</div>`;
  }).join('');
  return `<article class="core-card ${kind}${detailed ? ' core-card-detailed' : ''}"><span class="micro">${kind.toUpperCase()} / ${escape(core.slot)}${detailed ? ` ${escape(core.position)}` : ''}</span><div class="core-title">${arkCategoryIcon(kind, core.slot)}<h4>${escape(core.name)}</h4></div>${coreRaritySummary(core)}${core.description ? `<p>${escape(core.description)}</p>` : ''}${core.expandable ? `<details class="core-details"><summary>Breakpoints · 10P / 14P / 17P / 18–20P</summary>${points}</details>` : points}${core.source ? `<a class="source-tag" href="${escape(sources.find((s) => s.id === core.source)?.url)}">${escape(sources.find((s) => s.id === core.source)?.type || 'Reference')} ↗</a>` : '<span class="micro">Core ofensivo</span>'}</article>`;
};
export const skillCard = (skill) => `<article class="skill-card ${skill.role === 'MAIN DAMAGE' ? 'damage' : ''}"><div class="skill-title">${asset(skill)}<div><h3>${escape(skill.name)}</h3>${skill.category ? badge(skill.category) : ''}${skill.tag ? badge(skill.tag, 'purple') : ''}${skill.key ? badge(`Key ${skill.key}`, 'purple') : ''}${skill.level ? badge(`Lv${skill.level}`) : ''}<span class="skill-role">${escape(skill.role)}</span></div>${skill.code ? `<code>${escape(skill.code)}</code>` : ''}</div>${skill.tripods.length ? `<div class="tripods" style="--tripod-count:${skill.tripods.length}">${skill.tripods.map((tripod, i) => `<div><span class="micro">Tier ${i + 1}</span><span>${escape(tripod)}</span></div>`).join('')}</div>` : ''}${skill.rune ? `<div class="skill-rune">${runeBadge(skill.rune, skill.rarity)}</div>` : ''}${skill.runeOptions ? Object.entries(skill.runeOptions).map(([kind, options]) => `<div class="skill-rune-options"><span class="micro">${escape({ recommended: 'Recommended', alternative: 'Alternative', situational: 'Situational' }[kind] || kind)}</span>${options.map(option => `<p>${runeBadge(option)}</p>`).join('')}</div>`).join('') : ''}${skill.note ? `<p class="skill-note">${escape(skill.note)}</p>` : ''}${skill.gemNote ? `<p class="skill-note"><strong>Gems:</strong> ${escape(skill.gemNote)}</p>` : ''}${skill.runeAlternative ? `<p class="skill-note">${escape(skill.runeAlternative)}</p>` : ''}</article>`;
export const gemTable = (ids, skills, recommendations = {}, type = 'Cooldown', targets = {}, reference = false, rankLabel = 'Prioridade', ranks = {}) => `<div class="gem-table" role="table" aria-label="${type} gems e prioridade"><div class="gem-row gem-head" role="row"><span role="columnheader">${escape(rankLabel)}</span><span role="columnheader">Skill</span><span role="columnheader">${reference ? 'Referência' : type === 'Cooldown' ? 'Recommended' : 'Efeito'}</span></div>${ids.map((id, i) => { const skill = skills.find((s) => s.id === id) || targets[id]; return `<div class="gem-row" role="row"><span class="rank" role="cell">${escape(ranks[id] || String(i + 1).padStart(2, '0'))}</span><span class="gem-skill" role="cell">${asset(skill, 'small')}<strong>${escape(skill.name)}</strong></span><span class="${recommendations[id] ? 'accent' : ''}" role="cell">${escape(recommendations[id] || (type === 'Cooldown' ? 'Conforme o ciclo' : 'Damage Gem'))}</span></div>`; }).join('')}</div>`;
export const rotationBlock = (block, guide) => `<article class="rotation-block" id="block-${escape(block.id)}"><div class="block-label"><span>${escape(block.id)}</span><div><h3>Block ${escape(block.id)}</h3><p>Persona Generation</p></div></div><div class="rotation-skills">${block.skills.map((id, i) => { const skill = guide.skills.find((s) => s.id === id); return `${i ? '<span class="arrow" aria-hidden="true">→</span>' : ''}<div class="rotation-skill">${asset(skill)}<span>${escape(skill.name)}</span>${block.note && i === 0 ? `<small>${escape(block.note)}</small>` : ''}</div>`; }).join('')}</div><div class="block-finish">${flow(guide.rotation.afterBlock)}</div></article>`;
export const rotationSequence = (guide) => `<div class="panel base-loop"><div class="panel-heading"><div><span class="micro">Base Loop</span><h3>Um ciclo, ${guide.rotation.baseLoop.length} blocos.</h3></div><button id="expand-loop" aria-expanded="false" aria-controls="expanded-loop">Expanded <span aria-hidden="true">＋</span></button></div><div class="loop-flow">${guide.rotation.baseLoop.map((id, i) => `${i ? '<span class="arrow" aria-hidden="true">→</span>' : ''}<a href="#block-${escape(id)}" aria-label="Passo ${i + 1}: Block ${escape(id)}">${escape(id)}</a>`).join('')}<span class="repeat">↻ Repeat</span></div><ol id="expanded-loop" hidden>${guide.rotation.baseLoop.map((id) => { const block = guide.rotation.blocks.find((b) => b.id === id); return `<li><strong>Block ${escape(id)}</strong>${flow(block.skills.map((skillId) => guide.skills.find((s) => s.id === skillId).name + (block.note && skillId === block.skills[0] ? ` · ${block.note}` : '')))}<span class="expanded-finish">${escape(guide.rotation.afterBlock.slice(0, -1).join(' → '))} → ${escape(guide.rotation.swoops.map((skillId) => guide.skills.find((s) => s.id === skillId).name).join(' / '))}</span></li>`; }).join('')}</ol><p>Após cada bloco: ${escape(guide.rotation.afterBlock.slice(0, -1).join(' → '))} → ${escape(guide.rotation.swoops.map((id) => guide.skills.find((s) => s.id === id).name).join(' / '))}.</p></div>`;
export const recoveryCard = (item, i) => `<article class="recovery-card"><span class="micro">Case ${String(i + 1).padStart(2, '0')}</span><h3>${escape(item.title)}</h3><p>${escape(item.action)}</p>${item.note ? `<small>${escape(item.note)}</small>` : ''}</article>`;
export const engravingList = (items) => `<ul class="engraving-list">${items.map((item) => `<li>${getEngravingIcon(item) ? `<img src="./${escape(getEngravingIcon(item))}" width="32" height="32" alt="" loading="lazy" data-fallback>` : '<span aria-hidden="true">◇</span>'}${escape(item)}</li>`).join('')}</ul>`;
export const sourceReference = (source) => `<article class="source-reference"><div>${badge(source.type, source.type === 'Official' ? 'green' : '')}<a href="${escape(source.url)}" target="_blank" rel="noopener noreferrer">${escape(source.title)} ↗</a></div><p>${escape(source.note)}</p></article>`;
